### ISSUE TITLE
Feature Request - Render CardStack with a Card already open

### ISSUE THREAD

**Issue by evliu** [cameronbourke/react-cardstack#16]
Would it be difficult to have the CardStack already open to a Card on render?

**Comment by cameronbourke** [comment]
@evliu Thanks for the issue! This should be really simple, I'm not currently working on this project, but if you wanted to create a PR, I would be more than happy to review and help?

**Comment by evliu** [comment]
If you could get me started on where to look, I'd love to take a look

**Comment by cameronbourke** [comment]
@evliu Sure!

In `CardStack.js` line 17, the `topOffsets` property determines how much each card is displaced vertically.
```
this.state = {
  topOffsets: this.initialTopOffsets,
  cardSelected: false,
};
```

In the constructor for `CardStack` you will see that `initialTopOffsets` is being set.
```
this.initialTopOffsets = props.children.map((child, i) => equalsZero(i) ? 0 : headerHeight * i);
```
You will just need to update this line so that if a user passes a default card index to be open, it sets the offset for that index and the rest to 0. For example, if the user wants to show card index `2`, and they 4 cards in total, then the `initialTopOffsets` array needs to look like; `[0, 0, this.props.height, 0]`.

Hope that helps!

**Comment by evliu** [comment]
PR #17

**Comment by cameronbourke** [comment]
@evliu Thanks for the PR! A new version is now live on `npm`, https://www.npmjs.com/package/react-cardstack.
